backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
collections:
  - name: "blog"
    label: "Blog"
    label_singular: 'Blog'
    folder: "src/posts"
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: "", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}

      